version: '3.1'

networks:
  wp_llms_local: {}

services:

  wordpress:
    image: wordpress
    networks:
      - wp_llms_local
    restart: always
    ports:
      - ${WORDPRESS_PORT:-8080}:80
    environment:
      WORDPRESS_DB_HOST: mysql:3306
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-db_user}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-db_pass}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-wp_llms}
      WORDPRESS_PORT: ${WORDPRESS_PORT:-8080}
      WORDPRESS_TITLE: ${WORDPRESS_TITLE:-LifterLMS WordPress Development}
      WORDPRESS_USER_EMAIL: ${WORDPRESS_USER_EMAIL:-admin@wpllms.test}
      WORDPRESS_USER_NAME: ${WORDPRESS_USER_NAME:-admin}
      WORDPRESS_USER_PASS: ${WORDPRESS_USER_PASS:-password}
    volumes:
      - wordpress:/var/www/html
      - ./vendor/lifterlms/lifterlms-tests/docker/scripts:/scripts
    command: bash /scripts/container-command.sh

  mysql:
    image: mariadb
    networks:
      - wp_llms_local
    restart: always
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-wp_llms}
      MYSQL_USER: ${WORDPRESS_DB_USER:-db_user}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-db_pass}
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - mysql:/var/lib/mysql

volumes:
  wordpress:
  mysql:
